[tool.poetry]
name = "pyvera"
version = "0.3.15"
description = "Python API for talking to Veracontrollers"

license = "GPL2"

authors = [
    "James Cole",
    "Greg Dowling <mail@gregdowling.com>"
]

readme = 'README.md'

repository = "https://github.com/maximvelichko/pyvera"
homepage = "https://github.com/maximvelichko/pyvera"

keywords = ['vera', 'api']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
requests = ">=2.22.0"

[tool.poetry.dev-dependencies]
black = {version = "==23.10.1", python = "^3.7"}
coverage = "==7.3.2"
flake8 = "==3.7.8"
isort = "==4.3.21"
mypy = "==1.6.1"
pydocstyle = "==4.0.1"
pylint = "==3.0.2"
pytest = "==7.4.2"
pytest-cov = "==4.1.0"
responses = "==0.10.6"
toml = "==0.10.0"  # Needed by isort and others.
wheel = "==0.33.6"  # Needed for successful compile of other modules.

[tool.black]
target-version = ["py35", "py36", "py37", "py38"]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | build
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort
# https://github.com/timothycrosley/isort/wiki/isort-Settings
# splits long import on multiple lines indented by 4 spaces
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
indent = "    "
# by default isort don't check module indexes
not_skip =  "__init__.py"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
sections = "FUTURE,STDLIB,INBETWEENS,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
known_first_party = "homeassistant,tests"
forced_separate = "tests"
combine_as_imports = true
